# Generated by Django 6.0 on 2026-01-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "客户", "verbose_name_plural": "客户"},
        ),
        migrations.AlterModelOptions(
            name="instrument",
            options={"verbose_name": "仪器设备", "verbose_name_plural": "仪器设备"},
        ),
        migrations.AlterModelOptions(
            name="sample",
            options={"verbose_name": "样品", "verbose_name_plural": "样品"},
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={"verbose_name": "样品类型", "verbose_name_plural": "样品类型"},
        ),
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "测试记录", "verbose_name_plural": "测试记录"},
        ),
        migrations.AlterModelOptions(
            name="testtype",
            options={"verbose_name": "测试类型", "verbose_name_plural": "测试类型"},
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_person",
            field=models.CharField(max_length=255, verbose_name="联系人"),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="电子邮件"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, verbose_name="客户名称"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="calibration_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="校准日期"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="location",
            field=models.CharField(max_length=255, verbose_name="存放位置"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="model",
            field=models.CharField(max_length=255, verbose_name="仪器型号"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="name",
            field=models.CharField(max_length=255, verbose_name="仪器名称"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="next_calibration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="下次校准日期"
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="serial_number",
            field=models.CharField(max_length=100, verbose_name="序列号"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.client",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="collection_date",
            field=models.DateTimeField(verbose_name="采集日期"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="received_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="接收日期"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="样品编号"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sampletype",
                verbose_name="样品类型",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("in_progress", "处理中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="description",
            field=models.TextField(blank=True, verbose_name="类型描述"),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="类型名称"),
        ),
        migrations.AlterField(
            model_name="sampletype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="test",
            name="analysis_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="分析日期"),
        ),
        migrations.AlterField(
            model_name="test",
            name="analyzed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyzed_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="分析人员",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="test",
            name="result",
            field=models.CharField(blank=True, max_length=100, verbose_name="测试结果"),
        ),
        migrations.AlterField(
            model_name="test",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.sample",
                verbose_name="样品",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待测试"),
                    ("in_progress", "测试中"),
                    ("completed", "已完成"),
                    ("failed", "测试失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.testtype",
                verbose_name="测试类型",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="test",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="验证日期"),
        ),
        migrations.AlterField(
            model_name="test",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="验证人员",
            ),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="测试描述"),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="测试名称"),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="reference_range",
            field=models.CharField(max_length=100, verbose_name="参考范围"),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="unit",
            field=models.CharField(max_length=50, verbose_name="测试单位"),
        ),
        migrations.AlterField(
            model_name="testtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
