# Generated by Django 6.0 on 2026-01-12 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_client_options_alter_instrument_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="标准名称")),
                (
                    "standard_type",
                    models.CharField(max_length=255, verbose_name="标准类型"),
                ),
                (
                    "standard_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标准编号"
                    ),
                ),
                ("collection_date", models.DateTimeField(verbose_name="采集日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待实行"),
                            ("in_progress", "试行中"),
                            ("completed", "已实行"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "标准",
                "verbose_name_plural": "标准",
            },
        ),
    ]
