# Generated by Django 6.0 on 2026-01-12 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="订单编号",
            ),
        ),
        migrations.CreateModel(
            name="Project_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="方案编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="方案名称")),
                ("description", models.TextField(blank=True, verbose_name="方案描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="方案状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.client",
                        verbose_name="客户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "samples",
                    models.ManyToManyField(to="core.sample", verbose_name="样品"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_project_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "standards",
                    models.ManyToManyField(to="core.standard", verbose_name="标准"),
                ),
                (
                    "test_types",
                    models.ManyToManyField(to="core.testtype", verbose_name="测试类型"),
                ),
            ],
            options={
                "verbose_name": "方案",
                "verbose_name_plural": "方案",
            },
        ),
    ]
