# Generated by Django 6.0 on 2026-01-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_order_order_id_project_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_order",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_project_orders",
                to="core.staff",
                verbose_name="员工",
            ),
        ),
    ]
