# Generated by Django 6.0 on 2026-01-13 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_project_order_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="报告编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="报告名称")),
                ("description", models.TextField(blank=True, verbose_name="报告描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "报告编制"),
                            ("in_progress", "报告审核"),
                            ("completed", "报告签发"),
                            ("cancelled", "报告作废"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="报告状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.client",
                        verbose_name="客户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "samples",
                    models.ManyToManyField(to="core.sample", verbose_name="样品"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to="core.staff",
                        verbose_name="员工",
                    ),
                ),
                (
                    "standards",
                    models.ManyToManyField(to="core.standard", verbose_name="标准"),
                ),
                (
                    "test_types",
                    models.ManyToManyField(to="core.testtype", verbose_name="测试类型"),
                ),
            ],
            options={
                "verbose_name": "报告",
                "verbose_name_plural": "报告",
            },
        ),
    ]
