# Generated by Django 6.0 on 2026-01-13 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="project_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project_order",
                verbose_name="关联的方案",
            ),
        ),
    ]
