# Generated by Django 6.0 on 2026-01-13 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_report_project_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="description",
            field=models.TextField(blank=True, verbose_name="测试描述"),
        ),
        migrations.AddField(
            model_name="standard",
            name="reference_range",
            field=models.CharField(default="", max_length=100, verbose_name="参考范围"),
        ),
        migrations.AddField(
            model_name="standard",
            name="test_name",
            field=models.CharField(default="", max_length=255, verbose_name="测试名称"),
        ),
        migrations.AddField(
            model_name="standard",
            name="unit",
            field=models.CharField(default="", max_length=50, verbose_name="测试单位"),
        ),
        migrations.AlterField(
            model_name="project_order",
            name="standards",
            field=models.ManyToManyField(
                related_name="project_order_standards",
                to="core.standard",
                verbose_name="标准",
            ),
        ),
        migrations.AlterField(
            model_name="project_order",
            name="test_types",
            field=models.ManyToManyField(
                related_name="project_order_test_types",
                to="core.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="standards",
            field=models.ManyToManyField(
                related_name="report_standards", to="core.standard", verbose_name="标准"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="test_types",
            field=models.ManyToManyField(
                related_name="report_test_types",
                to="core.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.DeleteModel(
            name="TestType",
        ),
    ]
