# Generated by Django 6.0 on 2026-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_test_test_type_standard_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="员工编号",
            ),
        ),
    ]
