# Generated by Django 6.0 on 2026-01-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_staff_staff_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "permissions": (
                    ("can_approve_report", "可以审核报告"),
                    ("can_sign_report", "可以签发报告"),
                    ("can_reject_report", "可以拒绝报告"),
                ),
                "verbose_name": "报告",
                "verbose_name_plural": "报告",
            },
        ),
    ]
