# Generated by Django 6.0 on 2026-01-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_report_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_order",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="report",
            name="staff",
        ),
        migrations.AddField(
            model_name="project_order",
            name="staff",
            field=models.ManyToManyField(
                related_name="assigned_project_orders",
                to="core.staff",
                verbose_name="员工",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="staff",
            field=models.ManyToManyField(
                related_name="assigned_reports", to="core.staff", verbose_name="员工"
            ),
        ),
    ]
