# Generated by Django 6.0 on 2026-01-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_staff_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("radiation", "放射检测部"),
                    ("nuclear_safety", "核安全部"),
                    ("sample_management", "样品管理部"),
                    ("report_management", "报告管理部"),
                    ("quality_control", "质量控制部"),
                    ("r_d", "技术研发部"),
                    ("administration", "行政部"),
                    ("finance", "财务部"),
                ],
                max_length=50,
                null=True,
                verbose_name="部门",
            ),
        ),
    ]
