# Generated by Django 6.0 on 2026-01-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_staff_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(
                default="未分配", max_length=255, verbose_name="部门"
            ),
        ),
    ]
