# Generated by Django 6.0 on 2026-01-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_department_alter_staff_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.order",
                verbose_name="订单",
            ),
        ),
    ]
