# Generated by Django 6.0 on 2026-03-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_sample_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="detect_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acceptance", "验收检测"),
                    ("status", "状态检测"),
                    ("stability", "稳定性检测"),
                ],
                max_length=20,
                verbose_name="检测状态",
            ),
        ),
    ]
