# Generated by Django 6.0 on 2026-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_standard_detect_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="acceptance_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="验收检测参考范围"
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="acceptance_unit",
            field=models.CharField(
                default="", max_length=50, verbose_name="验收检测单位"
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="stability_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="稳定性检测参考范围"
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="stability_unit",
            field=models.CharField(
                default="", max_length=50, verbose_name="稳定性检测单位"
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="status_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="状态检测参考范围"
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="status_unit",
            field=models.CharField(
                default="", max_length=50, verbose_name="状态检测单位"
            ),
        ),
    ]
