# Generated by Django 6.0 on 2026-03-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_standard_acceptance_reference_range_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="acceptance_unit",
        ),
        migrations.RemoveField(
            model_name="standard",
            name="stability_unit",
        ),
        migrations.RemoveField(
            model_name="standard",
            name="status_unit",
        ),
    ]
