# Generated by Django 6.0 on 2026-03-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_standard_acceptance_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="reference_range",
        ),
    ]
