# Generated by Django 6.0 on 2026-03-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_standard_reference_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="detect_status",
        ),
    ]
