# Generated by Django 6.0 on 2026-03-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_standard_detect_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="standard_id",
            field=models.CharField(max_length=50, verbose_name="标准编号"),
        ),
    ]
