# Generated by Django 6.0 on 2026-03-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_standardlibrary_standard_library"),
        ("standard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="standard.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.RemoveField(
            model_name="standardlibrary",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="project_order",
            name="standards",
            field=models.ManyToManyField(
                related_name="project_order_standards",
                to="standard.standard",
                verbose_name="标准",
            ),
        ),
        migrations.AlterField(
            model_name="project_order",
            name="test_types",
            field=models.ManyToManyField(
                related_name="project_order_test_types",
                to="standard.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="standards",
            field=models.ManyToManyField(
                related_name="report_standards",
                to="standard.standard",
                verbose_name="标准",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="test_types",
            field=models.ManyToManyField(
                related_name="report_test_types",
                to="standard.standard",
                verbose_name="测试类型",
            ),
        ),
        migrations.DeleteModel(
            name="Standard",
        ),
        migrations.DeleteModel(
            name="StandardLibrary",
        ),
    ]
