# Generated by Django 6.0 on 2026-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_test_test_type_and_more"),
        ("standard", "0003_alter_standard_radiation_hygiene_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_order",
            name="standards",
            field=models.ManyToManyField(
                related_name="project_order_standards",
                to="standard.standard_radiation_hygiene",
                verbose_name="标准",
            ),
        ),
    ]
