# Generated by Django 6.0 on 2026-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_report_test_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="report_pdfs/", verbose_name="PDF文件"
            ),
        ),
    ]
