# Generated by Django 6.0 on 2026-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_report_pdf_file"),
        ("standard", "0005_remove_standardlibrary_standards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="standards",
            field=models.ManyToManyField(
                related_name="report_standards",
                to="standard.standard_radiation_hygiene",
                verbose_name="标准",
            ),
        ),
    ]
