# Generated by Django 6.0 on 2026-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_report_standards"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="position",
            field=models.CharField(default="", max_length=255, verbose_name="职务"),
        ),
    ]
