# Generated by Django 6.0 on 2026-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_staff_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="城市"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="province",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="省份"
            ),
        ),
    ]
