# Generated by Django 6.0 on 2026-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_client_city_client_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="纬度"),
        ),
        migrations.AddField(
            model_name="client",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="经度"),
        ),
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="城市"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="province",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="省份"
            ),
        ),
    ]
