# Generated by Django 6.0 on 2026-04-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_client_latitude_client_longitude_alter_client_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="client",
            name="longitude",
        ),
    ]
