# Generated by Django 6.0 on 2026-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_sampletypedescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_order",
            name="samples",
        ),
        migrations.AddField(
            model_name="project_order",
            name="sample_type_descriptions",
            field=models.ManyToManyField(
                to="core.sampletypedescription", verbose_name="样品类型描述"
            ),
        ),
        migrations.AddField(
            model_name="project_order",
            name="sample_types",
            field=models.ManyToManyField(to="core.sampletype", verbose_name="样品类型"),
        ),
    ]
