# Generated by Django 6.0 on 2026-04-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_staff_position_position_staff_position_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="position_fk",
            new_name="position_link",
        ),
    ]
