# Generated by Django 6.0 on 2026-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_rename_position_fk_staff_position_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_order",
            name="sample_type_description_quantities",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="样品描述数量"
            ),
        ),
    ]
