# Generated by Django 6.0 on 2026-05-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_add_sample_type_description_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="project_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="core.project_order",
                verbose_name="方案",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sampletypedescription",
                verbose_name="样品类型描述",
            ),
        ),
    ]
