# Generated by Django 6.0 on 2026-05-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_project_order_to_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="address",
            field=models.TextField(blank=True, verbose_name="地址信息"),
        ),
        migrations.AddField(
            model_name="test",
            name="field_data",
            field=models.TextField(blank=True, verbose_name="现场数据"),
        ),
    ]
