# Generated by Django 6.0 on 2026-05-06 03:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_test_address_test_field_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.get_test_image_path,
                verbose_name="测试照片",
            ),
        ),
    ]
