# Generated by Django 6.0 on 2026-05-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_test_photo"),
        ("standard", "0005_remove_standardlibrary_standards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="test_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="standard.standard",
                verbose_name="测试类型",
            ),
        ),
    ]
