# Generated by Django 6.0 on 2026-05-06 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_test_test_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="can_manage_clients",
            field=models.BooleanField(default=False, verbose_name="客户管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_orders",
            field=models.BooleanField(default=False, verbose_name="订单管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_reports",
            field=models.BooleanField(default=False, verbose_name="报告管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_samples",
            field=models.BooleanField(default=False, verbose_name="样品管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_staff",
            field=models.BooleanField(default=False, verbose_name="员工管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_tests",
            field=models.BooleanField(default=False, verbose_name="测试管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="启用登录"),
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_staff",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
    ]
