# Generated by Django 6.0 on 2026-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_staff_can_manage_clients_staff_can_manage_orders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="can_manage_org",
            field=models.BooleanField(default=False, verbose_name="组织架构"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_projects",
            field=models.BooleanField(default=False, verbose_name="方案管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_sample_descriptions",
            field=models.BooleanField(default=False, verbose_name="样品类型描述"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_sample_types",
            field=models.BooleanField(default=False, verbose_name="样品类型管理"),
        ),
        migrations.AddField(
            model_name="staff",
            name="can_manage_standard",
            field=models.BooleanField(default=False, verbose_name="标准管理"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="can_manage_samples",
            field=models.BooleanField(default=False, verbose_name="样本管理"),
        ),
    ]
