# Generated by Django 6.0 on 2026-05-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_staff_can_manage_org_staff_can_manage_projects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="can_access_admin",
            field=models.BooleanField(default=False, verbose_name="管理后台"),
        ),
    ]
