# Generated by Django 6.0 on 2026-05-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_staff_can_access_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="test_type",
        ),
    ]
