# Generated by Django 6.0 on 2026-05-07 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_remove_test_type_from_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_order",
            name="test_types",
        ),
        migrations.RemoveField(
            model_name="report",
            name="test_types",
        ),
    ]
