# Generated by Django 6.0 on 2026-05-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_remove_test_types_from_project_and_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampletypedescription",
            name="unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="量纲"),
        ),
        migrations.AddField(
            model_name="test",
            name="unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="量纲"),
        ),
    ]
