# Generated by Django 6.0 on 2026-05-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_add_unit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampletypedescription",
            name="base_unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="基础单位"),
        ),
        migrations.AddField(
            model_name="test",
            name="base_unit",
            field=models.CharField(blank=True, max_length=50, verbose_name="基础单位"),
        ),
        migrations.AddField(
            model_name="test",
            name="base_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=20,
                null=True,
                verbose_name="基础值",
            ),
        ),
    ]
