# Generated by Django 6.0 on 2026-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_add_base_unit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_order",
            name="cosmic_ray_info",
            field=models.JSONField(
                blank=True, default=list, verbose_name="宇宙射线信息"
            ),
        ),
        migrations.AddField(
            model_name="project_order",
            name="instrument_info",
            field=models.JSONField(blank=True, default=list, verbose_name="仪器信息"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_basis",
            field=models.CharField(blank=True, max_length=255, verbose_name="监测依据"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_conditions",
            field=models.TextField(blank=True, verbose_name="测量工况"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_humidity",
            field=models.CharField(blank=True, max_length=20, verbose_name="湿度"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_location",
            field=models.CharField(blank=True, max_length=255, verbose_name="监测地点"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_monitoring_date",
            field=models.CharField(blank=True, max_length=50, verbose_name="监测日期"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_project_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="项目名称"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_temperature",
            field=models.CharField(blank=True, max_length=20, verbose_name="温度"),
        ),
        migrations.AddField(
            model_name="project_order",
            name="radiation_weather",
            field=models.CharField(blank=True, max_length=100, verbose_name="天气状况"),
        ),
    ]
