# Generated by Django 6.0 on 2026-05-09 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_project_order_cosmic_ray_info_and_more"),
        ("standard", "0005_remove_standardlibrary_standards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project_order",
            index=models.Index(
                fields=["project_id"], name="idx_project_order_project_id"
            ),
        ),
        migrations.AddIndex(
            model_name="project_order",
            index=models.Index(fields=["status"], name="idx_project_order_status"),
        ),
        migrations.AddIndex(
            model_name="project_order",
            index=models.Index(
                fields=["created_at"], name="idx_project_order_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="project_order",
            index=models.Index(fields=["client"], name="idx_project_order_client"),
        ),
        migrations.AddIndex(
            model_name="project_order",
            index=models.Index(fields=["order"], name="idx_project_order_order"),
        ),
    ]
