# Generated by Django 6.0 on 2026-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_test_avg_value_test_cosmic_ray_test_elevation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="avg_value",
            field=models.FloatField(blank=True, null=True, verbose_name="平均值"),
        ),
        migrations.AlterField(
            model_name="test",
            name="cosmic_ray",
            field=models.FloatField(blank=True, null=True, verbose_name="宇宙射线"),
        ),
        migrations.AlterField(
            model_name="test",
            name="elevation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="高程（H）",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="k3",
            field=models.FloatField(blank=True, null=True, verbose_name="k3"),
        ),
        migrations.AlterField(
            model_name="test",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=15,
                null=True,
                verbose_name="纬度（N）",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=15,
                null=True,
                verbose_name="经度（E）",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="r_gamma_1",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(1)"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="r_gamma_2",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(2)"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="r_gamma_3",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(3)"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="r_gamma_4",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(4)"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="r_gamma_5",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(5)"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="std_value",
            field=models.FloatField(blank=True, null=True, verbose_name="标准差"),
        ),
    ]
