# Generated by Django 6.0 on 2026-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_test_avg_value_alter_test_cosmic_ray_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="r_gamma_10",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(10)"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="r_gamma_6",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(6)"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="r_gamma_7",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(7)"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="r_gamma_8",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(8)"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="r_gamma_9",
            field=models.FloatField(
                blank=True, null=True, verbose_name="仪器示值Rγ(9)"
            ),
        ),
    ]
