# Generated by Django 6.0 on 2026-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0002_standard_radiation_hygiene"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standard_radiation_hygiene",
            options={
                "verbose_name": "放射卫生标准",
                "verbose_name_plural": "放射卫生标准",
            },
        ),
        migrations.RemoveField(
            model_name="standard",
            name="stability_reference_range",
        ),
        migrations.RemoveField(
            model_name="standard",
            name="status_reference_range",
        ),
        migrations.AddField(
            model_name="standard_radiation_hygiene",
            name="stability_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="稳定性检测参考范围"
            ),
        ),
        migrations.AddField(
            model_name="standard_radiation_hygiene",
            name="status_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="状态检测参考范围"
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="acceptance_reference_range",
            field=models.CharField(default="", max_length=100, verbose_name="参考范围"),
        ),
        migrations.AlterField(
            model_name="standard_radiation_hygiene",
            name="acceptance_reference_range",
            field=models.CharField(
                default="", max_length=100, verbose_name="验收检测参考范围"
            ),
        ),
    ]
