# Generated by Django 6.0 on 2026-03-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0003_alter_standard_radiation_hygiene_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardlibrary",
            name="standards",
            field=models.ManyToManyField(
                blank=True,
                to="standard.standard_radiation_hygiene",
                verbose_name="标准",
            ),
        ),
    ]
