# Generated by Django 6.0 on 2026-03-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standard", "0004_standardlibrary_standards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardlibrary",
            name="standards",
        ),
    ]
